extends Node3D
## Runtime Terrain3D setup: loads the baked region data (tools/bake_terrain.gd),
## builds the PBR texture set (Poly Haven CC0) and turns on the auto-shader so
## grass covers the flat ground and rock shows through on the slopes. Collision
## is generated by Terrain3D itself.

const DATA_DIR := "res://assets/terrain"
const TEX := "res://assets/textures/terrain/"

# id -> [name, tile size (m), normal_depth, albedo tint]
const TEXTURES := [
	["lawn_grass", 2.6, 1.0, Color(0.82, 0.92, 0.68)],   # 0 = base  (flat ground)
	["gray_rocks", 5.5, 1.3, Color(0.95, 0.95, 0.95)],     # 1 = overlay (slopes)
	["forrest_ground_01", 3.2, 1.0, Color(1, 1, 1)],       # 2 = clearing / worn ground
]

var terrain: Node          # Terrain3D

func build(cam: Camera3D) -> void:
	var mat = ClassDB.instantiate("Terrain3DMaterial")
	mat.set("auto_shader", true)              # blend grass<->rock by slope
	mat.set("world_background", 1)            # 1 = Flat: extend the ground past the regions
	mat.set("dual_scaling", false)

	terrain = ClassDB.instantiate("Terrain3D")
	terrain.name = "Terrain3D"
	terrain.set("region_size", 256)
	terrain.set("vertex_spacing", 1.0)
	terrain.set("collision_mode", 1)          # 1 = Full / Game (static body)
	terrain.set("material", mat)
	add_child(terrain)
	terrain.set("data_directory", DATA_DIR)   # loads the baked regions

	# assign assets after the node is live (matches Terrain3D's own examples)
	var assets = ClassDB.instantiate("Terrain3DAssets")
	terrain.set("assets", assets)
	for i in TEXTURES.size():
		var e: Array = TEXTURES[i]
		var ta = ClassDB.instantiate("Terrain3DTextureAsset")
		ta.set("name", e[0])
		ta.set("id", i)
		ta.set("albedo_texture", _load(e[0] + "_alb_ht.webp"))
		ta.set("normal_texture", _load(e[0] + "_nrm_rgh.webp"))
		ta.set("uv_scale", 1.0 / e[1])
		ta.set("normal_depth", e[2])
		ta.set("albedo_color", e[3])
		assets.set_texture(i, ta)

	if cam:
		terrain.call("set_camera", cam)

	mat.set("show_checkered", false)
	mat.set("show_grey", false)

	# auto-shader: Terrain3D packs the FLAT texture into "overlay" and the SLOPE
	# texture into "base" (blend=1 on flat -> overlay). So overlay = grass, base = rock.
	mat.call("set_shader_param", "auto_base_texture", 1)      # slopes  -> gray_rocks
	mat.call("set_shader_param", "auto_overlay_texture", 0)   # flats   -> lawn_grass
	mat.call("set_shader_param", "auto_slope", 2.6)
	mat.call("set_shader_param", "auto_height_reduction", 0.0)
	mat.call("set_shader_param", "blend_sharpness", 0.85)
	mat.call("set_shader_param", "enable_macro_variation", true)
	mat.call("set_shader_param", "macro_variation_slope", 0.35)

func height(pos: Vector3) -> float:
	if terrain == null:
		return 0.0
	var h: float = terrain.get("data").call("get_height", pos)
	return 0.0 if is_nan(h) else h

func _load(f: String) -> Texture2D:
	var p := TEX + f
	return load(p) if ResourceLoader.exists(p) else null
